-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 14:53:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema we_source
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema we_source
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `we_source` DEFAULT CHARACTER SET utf8 ;
USE `we_source` ;

-- -----------------------------------------------------
-- Table `we_source`.`ws_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_country` (
  `ws_country_id` INT NOT NULL AUTO_INCREMENT,
  `ws_country_name` VARCHAR(45) NULL,
  `ws_country_phonecode` VARCHAR(45) NULL,
  PRIMARY KEY (`ws_country_id`),
  UNIQUE INDEX `ws_country_id_UNIQUE` (`ws_country_id` ASC) VISIBLE,
  UNIQUE INDEX `ws_country_phonecode_UNIQUE` (`ws_country_phonecode` ASC) VISIBLE,
  UNIQUE INDEX `ws_country_name_UNIQUE` (`ws_country_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_state` (
  `ws_state_id` INT NOT NULL,
  `ws_state_name` VARCHAR(45) NULL,
  `ws_state_short_name` VARCHAR(3) NULL,
  PRIMARY KEY (`ws_state_id`),
  UNIQUE INDEX `ws_state_id_UNIQUE` (`ws_state_id` ASC) VISIBLE,
  UNIQUE INDEX `ws_state_name_UNIQUE` (`ws_state_name` ASC) VISIBLE,
  UNIQUE INDEX `ws_state_short_name_UNIQUE` (`ws_state_short_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_seeker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_seeker` (
  `apl_seeker_id` INT NOT NULL AUTO_INCREMENT,
  `apl_seeker_name` VARCHAR(50) NULL,
  `apl_seeker_email` VARCHAR(70) NULL,
  `apl_seeker_mobile` INT NULL,
  `apl_seeker_gender` CHAR(1) NULL,
  `apl_seeker_addr1` VARCHAR(45) NULL,
  `apl_seeker_addr2` VARCHAR(45) NULL,
  `apl_seeker_addr3` VARCHAR(45) NULL,
  `apl_seeker_addr4` VARCHAR(45) NULL,
  `apl_seeker_city` VARCHAR(30) NULL,
  `apl_seeker_state` INT NULL,
  `apl_seeker_country` INT NOT NULL,
  `apl_seeker_postcode` INT NULL,
  `apl_seeker_dob` DATE NULL,
  `apl_seeker_created_by` INT NULL,
  `apl_seeker_created_date` DATETIME NULL,
  `apl_seeker_last_updated_by` INT NULL,
  `apl_seeker_last_updated_date` DATETIME NULL,
  PRIMARY KEY (`apl_seeker_id`, `apl_seeker_country`),
  UNIQUE INDEX `seeker_id_UNIQUE` (`apl_seeker_id` ASC) VISIBLE,
  UNIQUE INDEX `apl_email_UNIQUE` (`apl_seeker_email` ASC) VISIBLE,
  UNIQUE INDEX `ws_seeker_mobile_UNIQUE` (`apl_seeker_mobile` ASC) VISIBLE,
  INDEX `fk_seeker_country_id_idx` (`apl_seeker_country` ASC) VISIBLE,
  INDEX `fk_seeker_country_id_idx1` (`apl_seeker_state` ASC) VISIBLE,
  CONSTRAINT `fk_seeker_country_id`
    FOREIGN KEY (`apl_seeker_country`)
    REFERENCES `we_source`.`ws_country` (`ws_country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seeker_state_id`
    FOREIGN KEY (`apl_seeker_state`)
    REFERENCES `we_source`.`ws_state` (`ws_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_publisher` (
  `adm_publisher_id` INT NOT NULL AUTO_INCREMENT,
  `adm_publisher_name` VARCHAR(50) NULL,
  `adm_publisher_email` VARCHAR(70) NULL,
  `adm_publisher_mobile` INT NULL,
  `adm_publisher_gender` CHAR(1) NULL,
  `adm_publisher_addr1` VARCHAR(45) NULL,
  `adm_publisher_addr2` VARCHAR(45) NULL,
  `adm_publisher_addr3` VARCHAR(45) NULL,
  `adm_publisher_addr4` VARCHAR(45) NULL,
  `adm_publisher_city` VARCHAR(30) NULL,
  `adm_publisher_state` INT NULL,
  `adm_publisher_country` INT NOT NULL,
  `adm_publisher_postcode` INT NULL,
  `adm_publisher_dob` DATE NULL,
  `adm_publisher_created_by` INT NULL,
  `adm_publisher_created_date` DATE NULL,
  `adm_publisher_last_updated_by` INT NULL,
  `adm_publisher_last_updated_date` DATETIME NULL,
  PRIMARY KEY (`adm_publisher_id`, `adm_publisher_country`),
  UNIQUE INDEX `seeker_id_UNIQUE` (`adm_publisher_id` ASC) VISIBLE,
  UNIQUE INDEX `apl_email_UNIQUE` (`adm_publisher_email` ASC) VISIBLE,
  UNIQUE INDEX `ws_seeker_mobile_UNIQUE` (`adm_publisher_mobile` ASC) VISIBLE,
  CONSTRAINT `fk_publisher_country_id`
    FOREIGN KEY (`adm_publisher_country`)
    REFERENCES `we_source`.`ws_country` (`ws_country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publisher_state_id`
    FOREIGN KEY (`adm_publisher_state`)
    REFERENCES `we_source`.`ws_state` (`ws_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_job_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_job_category` (
  `ws_job_category_id` INT NOT NULL AUTO_INCREMENT,
  `ws_job_category_title` VARCHAR(20) NOT NULL,
  `ws_job_category_description` VARCHAR(45) NULL,
  UNIQUE INDEX `ws_job_category_title_UNIQUE` (`ws_job_category_title` ASC) VISIBLE,
  PRIMARY KEY (`ws_job_category_id`),
  UNIQUE INDEX `ws_job_category_id_UNIQUE` (`ws_job_category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_job_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_job_status` (
  `ws_job_status_id` INT NOT NULL AUTO_INCREMENT,
  `ws_job_status_title` VARCHAR(15) NOT NULL,
  `ws_job_status_description` VARCHAR(45) NULL,
  PRIMARY KEY (`ws_job_status_id`),
  UNIQUE INDEX `ws_job_status_id_UNIQUE` (`ws_job_status_id` ASC) VISIBLE,
  UNIQUE INDEX `ws_job_status_title_UNIQUE` (`ws_job_status_title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_job_fee_interval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_job_fee_interval` (
  `ws_job_fee_interval_id` INT NOT NULL AUTO_INCREMENT,
  `ws_job_fee_interval_title` VARCHAR(15) NULL,
  `ws_job_fee_interval_description` VARCHAR(45) NULL,
  PRIMARY KEY (`ws_job_fee_interval_id`),
  UNIQUE INDEX `ws_job_fee_interval_id_UNIQUE` (`ws_job_fee_interval_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_job_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_job_period` (
  `ws_job_period_id` INT NOT NULL AUTO_INCREMENT,
  `ws_job_period_title` VARCHAR(10) NULL,
  `ws_job_period_description` VARCHAR(45) NULL,
  PRIMARY KEY (`ws_job_period_id`),
  UNIQUE INDEX `ws_job_period_id_UNIQUE` (`ws_job_period_id` ASC) VISIBLE,
  UNIQUE INDEX `ws_job_period_title_UNIQUE` (`ws_job_period_title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_job` (
  `ws_job_id` INT NOT NULL AUTO_INCREMENT,
  `ws_job_title` VARCHAR(45) NULL,
  `ws_job_from_date` VARCHAR(45) NULL,
  `ws_job_to_date` VARCHAR(45) NULL,
  `ws_job_period` INT NULL,
  `ws_job_category` INT NULL,
  `ws_job_status` INT NULL,
  `ws_job_proposed_fees` INT NULL,
  `ws_job_final_fees` INT NULL,
  `ws_job_fee_interval` INT NULL,
  `ws_job_description` VARCHAR(100) NULL,
  `ws_job_is_wfh` TINYINT NULL,
  `ws_job_created_by` INT NULL,
  `ws_job_created_date` DATETIME NULL,
  `ws_job_last_updated_by` INT NULL,
  `ws_job_last_updated_date` DATETIME NULL,
  PRIMARY KEY (`ws_job_id`),
  UNIQUE INDEX `ws_job_id_UNIQUE` (`ws_job_id` ASC) VISIBLE,
  INDEX `fk_job_created_by_id_idx` (`ws_job_created_by` ASC) VISIBLE,
  INDEX `fk_job_category_id_idx` (`ws_job_category` ASC) VISIBLE,
  INDEX `fk_job_status_id_idx` (`ws_job_status` ASC) VISIBLE,
  INDEX `fk_job_interval_id_idx` (`ws_job_fee_interval` ASC) VISIBLE,
  INDEX `fk_job_period_id_idx` (`ws_job_period` ASC) VISIBLE,
  CONSTRAINT `fk_job_created_by_id`
    FOREIGN KEY (`ws_job_created_by`)
    REFERENCES `we_source`.`ws_publisher` (`adm_publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_category_id`
    FOREIGN KEY (`ws_job_category`)
    REFERENCES `we_source`.`ws_job_category` (`ws_job_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_status_id`
    FOREIGN KEY (`ws_job_status`)
    REFERENCES `we_source`.`ws_job_status` (`ws_job_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_interval_id`
    FOREIGN KEY (`ws_job_fee_interval`)
    REFERENCES `we_source`.`ws_job_fee_interval` (`ws_job_fee_interval_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_period_id`
    FOREIGN KEY (`ws_job_period`)
    REFERENCES `we_source`.`ws_job_period` (`ws_job_period_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `we_source`.`ws_seeker_job_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `we_source`.`ws_seeker_job_mapping` (
  `ws_seeker_job_mapping_id` INT NOT NULL AUTO_INCREMENT,
  `apl_seeker_id` INT NULL,
  `ws_job_id` INT NULL,
  `ws_seeker_negotiate_fee` INT NULL,
  `ws_seeker_comment` VARCHAR(100) NULL,
  `ws_seeker_job_mapping_created_by` INT NULL,
  `ws_seeker_job_mapping_created_date` DATETIME NULL,
  `ws_seeker_job_mapping_last_updated_by` INT NULL,
  `ws_seeker_job_mapping_last_updated_date` DATETIME NULL,
  PRIMARY KEY (`ws_seeker_job_mapping_id`),
  UNIQUE INDEX `ws_seeker_job_mapping_id_UNIQUE` (`ws_seeker_job_mapping_id` ASC) VISIBLE,
  INDEX `fk_apl_seeker_ws_job_id_idx` (`apl_seeker_id` ASC) VISIBLE,
  INDEX `fk_ws_job_id_idx` (`ws_job_id` ASC) VISIBLE,
  CONSTRAINT `fk_apl_seeker_id`
    FOREIGN KEY (`apl_seeker_id`)
    REFERENCES `we_source`.`ws_seeker` (`apl_seeker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ws_job_id`
    FOREIGN KEY (`ws_job_id`)
    REFERENCES `we_source`.`ws_job` (`ws_job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
